# Generated by Django 4.1.6 on 2023-03-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='age',
        ),
    ]
