# Generated by Django 4.1.6 on 2023-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_additional_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_fee', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
