# Generated by Django 4.1.6 on 2023-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.TextField(max_length=255)),
                ('s_address', models.TextField(max_length=255)),
                ('s_dob', models.DateField(blank=True, null=True)),
                ('s_phone', models.IntegerField(blank=True, null=True)),
                ('s_education', models.CharField(max_length=255)),
                ('j_date', models.DateField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
    ]
