# Generated by Django 4.1.6 on 2023-03-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
