# Generated by Django 4.1.6 on 2023-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_staff_profile_staff_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
